// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/videos/VideoEnquete.tsx": () => import("../components/mockups/videos/VideoEnquete.tsx"),
  "./components/mockups/videos/VideoShowcase.tsx": () => import("../components/mockups/videos/VideoShowcase.tsx")
};
