// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nav-menu/GridCards.tsx": () => import("../components/mockups/nav-menu/GridCards.tsx"),
  "./components/mockups/nav-menu/HorizontalScroll.tsx": () => import("../components/mockups/nav-menu/HorizontalScroll.tsx")
};
